# We couldn't have the parcels dependency in the root as it would cause unnecessary noise in the lockfile
[workspace]
authors = ["parcels-benchmarks contributors"]
channels = ["conda-forge"]
name = "sandbox"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
preview = ['pixi-build']

[dependencies]

parcels = { path = '../Parcels' }

[pypi-dependencies]
parcels_benchmarks = { path = "..", editable = true }
