[workspace]
authors = ["parcels-benchmarks contributors"]
channels = ["conda-forge"]
name = "parcels-benchmarks"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

lint = "pre-commit run --all-files"

[dependencies]

python = "3.12.*"
pooch = ">=1.8.2"
asv = ">=0.6.5"
py-rattler = "0.15.*"

pre_commit = "*"
ty = "*"
typer = "*"

[pypi-dependencies]
parcels_benchmarks = { path = ".", editable = true }
