steps:
  - label: "Run all benchmarks (NVMe)"
    key: "test-nvme"
    command: |
      # Sets the data directory to local NVMe scratch disk
      export PARCELS_BENCHMARKS_DATA_FOLDER="/apps/parcels-ci"
      pixi install
      pixi run setup-data
      pixi run asv run

    env:
      slurm_partition: "main"
      slurm_time: "08:00:00"
      slurm_nodes: 1
      slurm_nodelist: "franklin"
      slurm_ntasks_per_node: 1
      slurm_cpus_per_task: 8
    agents:
      queue: "galapagos"
